language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t sanya29/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true sanya29/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react-aws" 
    env: "DockerReactAws-env"
    bucket_name: "elasticbeanstalk-us-east-2-055502182657"
    bucket_path: "docker-react-aws"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
