# The .dev exists to make sure that this Dockerfile is only used for development

FROM node:alpine

WORKDIR '/app'

COPY package.json .
RUN npm install

COPY . .

CMD ["npm", "run", "start"]